version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - messenger-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=messenger
      - SERVER_PORT=8080
      - CONFIG_FILE=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - messenger-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge

volumes:
  mongodb_data: 