name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/messenger
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/darigram:latest
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
          port: 22
          timeout: 30s
          command_timeout: 10m 